### ISSUE TITLE
Not working on Windows 10 (64bits)

### ISSUE THREAD

**Issue by TheDemystifier** [excitoon/video-remove-silence#10]
subprocess.call doesn't seem to be working on Windows :

```
Extracting audio...
Finding gaps...
Found 2 gaps, 1.2 seconds total
Traceback (most recent call last):
  File "video-remove-silence", line 162, in <module>
    frames = ffprobe.get_frames(args.path)
  File "G:\ffprobe.py", line 16, in get_frames
    for stream in _get_json(path)['streams']:
  File "G:\ffprobe.py", line 6, in _get_json
    result = subprocess.run(['ffprobe', path, '-loglevel', 'quiet', '-print_format', 'json', '-show_streams'], stdout=subprocess.PIPE)
  File "C:\Users\X\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\X\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\X\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by TheDemystifier** [comment]
FFmpeg wasn't configured well
